name: "nest_monolithic_base"
services:
  postgres:
    image: postgres:15-alpine
    container_name: nmb_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest_db
    ports:
      - "54321:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    container_name: nmb_redis
    image: redis:7-alpine
    ports:
      - "63791:6379"
    volumes:
      - redis_data:/data

  mailpit:
    container_name: nmb_mailpit
    image: axllent/mailpit:latest
    ports:
      - "10251:1025"  # SMTP port
      - "8025:8025"  # Web UI port

  minio:
    container_name: nmb_minio
    image: minio/minio:latest
    ports:
      - "9000:9000"  # API port
      - "9001:9001"  # Console port
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  postgres_data:
  redis_data:
  minio_data: